### ISSUE TITLE
admin doubling up on routes

### ISSUE THREAD

**Issue by beth-str** [beth-str/2015-02-13-week4-lodge#1]
When I first arrive at admin page, all the links appear to point to the right place (while hovering):
![screen shot 2015-02-17 at 6 36 04 pm](https://cloud.githubusercontent.com/assets/10066624/6240471/b1b527a0-b6d4-11e4-9aea-a6535a65c315.jpg)

But after I click _any_ of the menu items, the links all double the part of the path "admin" => "admin/admin/edit_reservation".

![screen shot 2015-02-17 at 6 36 15 pm](https://cloud.githubusercontent.com/assets/10066624/6240480/d11c7b20-b6d4-11e4-91c3-cd9ab0c58d8d.jpg)

I can't see why this is happening.  
My routes are here: https://github.com/beth-str/2015-02-13-week4-lodge/blob/191dedd0342d4da0031ade5d80f97e0b767e30ef/menu.rb#L71-L114
My menu is here: https://github.com/beth-str/2015-02-13-week4-lodge/blob/191dedd0342d4da0031ade5d80f97e0b767e30ef/views/layout_back.erb#L18-L42

Not sure what else to point to as the possible culprit.  So far I have:
-put all views in a single folder (no subfolders)
-changed my routes to not use a symbol
-changed my layout for the admin pages to a new name (not :admin) so that there couldn't be any confusion on that point...

**Comment by jhogrefe** [comment]
Isn't it because you are already at homepage/admin, so your new route path adds:

/admin/add_reservation

Have you tried shortening the route links to just:

/add_reservation

Could be totally wrong, but that is my first guess...

**Comment by sumeetjain** [comment]
The `href` is set to `admin/add_reservation`, which means that when you click it it looks at the current path and goes to `admin/add_reservation` _relative to the current path_.

This is as opposed to a path of `/admin/add_reservation`, which (because of the leading forward slash, which represents the server's root path) will not be relative to the current path.
